def exit_with_error(message=''):
    print(message)
    print('Exiting...')
    exit(1)
